### ISSUE TITLE
DataGrip failing Redshift connection with "Native Library cannot be loaded.  Can't obtain static method fromNative(Method, Object) from class com.sun.jna.Native".

### ISSUE THREAD

**Issue by dunkan21** [flathub/com.jetbrains.DataGrip#105]
Trying to use DataGrip to connect to a Redshift database on a Windows machine.  After adding two .jar files and testing the connection, it is giving the following error:

"Native Library cannot be loaded.  Can't obtain static method fromNative(Method, Object) from class com.sun.jna.Native".

Not having much luck finding information on what this error indicates, or how to go about resolving the issue.  Anybody seen this before or know what it is referring to?

**Comment by x80486** [comment]
@dunkan21, what exactly do you mean by _Trying to use DataGrip to connect to a Redshift database on a Windows machine_?

If you are using `DataGrip` on a `Windows` machine to connect to `Amazon Redshift` this wouldn't exactly apply to the Flatpak version.

**Comment by dunkan21** [comment]
Thanks for that, I was unaware that I had specified Flatpak when creating the issue.  Any insight on the best forum to ask this question for Windows based OS?

**Comment by x80486** [comment]
This is your starting point: https://www.jetbrains.com/help/datagrip/getting-help.html
