### ISSUE TITLE
Datagrid running in container 

### ISSUE THREAD

**Issue by yhoungdev** [flathub/com.jetbrains.DataGrip#110]
Installed Datagrip on Kali from Flathub and got this message

![Screenshot from 2023-10-29 08-25-03](https://github.com/flathub/com.jetbrains.DataGrip/assets/54102389/22b25dee-5650-4982-9c0d-16644fee9b78)

**Comment by x80486** [comment]
What's the problem you would like to report?

**Comment by yhoungdev** [comment]
Like is it by default runned in a container, instead of user system ?

**Comment by x80486** [comment]
The Flatpak uses Lctrs/jetbrains-flatpak-wrapper to start. You are just looking at the usual startup message from the first run: https://raw.githubusercontent.com/Lctrs/jetbrains-flatpak-wrapper/master/first_run.txt

**Comment by yhoungdev** [comment]
wow this is awesome, thanks alot for this, God bless you
