### ISSUE TITLE
Unable to save settings

### ISSUE THREAD

**Issue by ghost** [flathub/com.jetbrains.DataGrip#116]
I keep receiving a spamming notification that DataGrip is unable to save any changes. I'm also unable to execute any code, rendering the entire application useless. I've checked Flatseal to ensure there are no permissions blocking storage access, but everything appears to be fine.
![Screenshot from 2024-01-10 17-56-30](https://github.com/flathub/com.jetbrains.DataGrip/assets/123986260/d50a227c-1aee-4f7f-9fe2-3d57c13c2f4c)

**Comment by x80486** [comment]
Looks like you are unable to write to the filesystem.

Anyway, what GNU/Linux are you using? — version included. And what are the steps to replicate this.

**Comment by x80486** [comment]
Double checked, and I'm able to work just fine with DataGrip in Arch Linux.

I've also tested the latest version in an Ubuntu VM to verify if there was something odd, but it looks like this is something with your system or Silverblue.

> Drivers are stored in `${HOME}/.var/app/com.jetbrains.DataGrip/config/JetBrains/{DATAGRIP_VERSION}/jdbc-drivers/` — you should be able to see something there.

I would verify if there are any issues with other Flatpak applications — other JetBrains' products (just testing the trial versions) and a random Flatpak application.

I use https://8n1.org/ to share logs. This is a service where you can't modify anything, so make sure you want to share those and that there is nothing particularly _sensitive_.

**Comment by x80486** [comment]
I meant that, regardless of the error message, you might see the drivers downloaded at that location — `${HOME}/.var/app/com.jetbrains.DataGrip/config/JetBrains/{DATAGRIP_VERSION}/jdbc-drivers/`. The XML file are the JDBC drivers you could download, but once any of those is actually downloaded, it will create a sub-directory in that path with the type, version, etc.

For the errors, DataGrip should store them in `${HOME}/.var/app/com.jetbrains.DataGrip/cache/JetBrains/{DATAGRIP_VERSION}/log/idea.log` — this file should give you the exact reason why DataGrip is unable to save anything.

**Comment by x80486** [comment]
Where is your project located at? Are you trying to save your project to `/app/share/jetbrains-flatpak-wrapper/`? If that's the case, it is not going to work for the reasons you mentioned before.

Try to use some other namespace within your home directory, for instance.
