### ISSUE TITLE
Unable to save settings

### ISSUE THREAD

**Issue by 4fort** [flathub/com.jetbrains.DataGrip#125]
`Failed to save settings. Please restart DataGrip` 

I cannot save the things I do in datagrip

**Comment by x80486** [comment]
Can you check the location you are working?

If you opened up the default location (`/app/share/jetbrains-flatpak-wrapper`) that is only presented only the very first time, you won't be able to save project-specific settings, because that location is read-only.

Let me know if that's the case. If so, close it, and create a new project. It will ask you for a new location, select anything that works for you within your home and you will be able to do (almost) everything as usual.

**Comment by 4fort** [comment]
![image](https://github.com/flathub/com.jetbrains.DataGrip/assets/61641669/e647a815-11ae-4ec5-a1eb-d325fbbd3e63)

is this the location that you mean? I tried changing that one and the Trusted Locations as well but still no success. I can use DataGrip and connect to my database but when I close it and open again it resets, however the settings like for instance the locations I have set in the attached image saves.

**Comment by x80486** [comment]
Can you post the output of any of these commands:

- `hostnamectl`
- `cat /etc/os-release`
- `uname -a`

Additionally, you can start the application with `flatpak run --verbose com.jetbrains.DataGrip` and see if there are any issues in the logs. You can post that as well — along with the screenshot where you say it fails to save the settings? Alternatively, the DataGrip's log file would be the same.

**Comment by 4fort** [comment]
`hostnamectl`
```
Static hostname: laptop-fedora
           Icon name: computer-laptop
             Chassis: laptop 💻
          Machine ID: 7412385004ab42eb87ce9a4dde5f1242
             Boot ID: 5d4b27aaa3a94a95b42c3a87cd23ddcc
    Operating System: Fedora Linux 40 (Workstation Edition)
         CPE OS Name: cpe:/o:fedoraproject:fedora:40
      OS Support End: Tue 2025-05-13
OS Support Remaining: 10month 2w 4d
              Kernel: Linux 6.9.5-200.fc40.x86_64
        Architecture: x86-64
     Hardware Vendor: Acer
      Hardware Model: Aspire A715-42G
    Firmware Version: V1.08
       Firmware Date: Wed 2021-09-15
        Firmware Age: 2y 9month 1w 1d 
```

`cat /etc/os-release`
```
NAME="Fedora Linux"
VERSION="40 (Workstation Edition)"
ID=fedora
VERSION_ID=40
VERSION_CODENAME=""
PLATFORM_ID="platform:f40"
PRETTY_NAME="Fedora Linux 40 (Workstation Edition)"
ANSI_COLOR="0;38;2;60;110;180"
LOGO=fedora-logo-icon
CPE_NAME="cpe:/o:fedoraproject:fedora:40"
DEFAULT_HOSTNAME="fedora"
HOME_URL="https://fedoraproject.org/"
DOCUMENTATION_URL="https://docs.fedoraproject.org/en-US/fedora/f40/system-administrators-guide/"
SUPPORT_URL="https://ask.fedoraproject.org/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"
REDHAT_BUGZILLA_PRODUCT="Fedora"
REDHAT_BUGZILLA_PRODUCT_VERSION=40
REDHAT_SUPPORT_PRODUCT="Fedora"
REDHAT_SUPPORT_PRODUCT_VERSION=40
SUPPORT_END=2025-05-13
VARIANT="Workstation Edition"
VARIANT_ID=workstation
```

`uname -a`

```
Linux laptop-fedora 6.9.5-200.fc40.x86_64 #1 SMP PREEMPT_DYNAMIC Sun Jun 16 15:47:09 UTC 2024 x86_64 GNU/Linux
```

**Comment by lpww** [comment]
I had the same issue but was able to resolve it by creating a new project before attempting to add my data source.

**Comment by x80486** [comment]
Take a look at the linked issue. Without the logs it's almost impossible to figure it out why DataGrip is unable to save this.

@lpww, you were likely using the default location that's displayed initially, and it's read-only. If you created a new project, you might have placed it within your home sub-directory, hence the `.idea/` sub-directory inside is writable.

**Comment by 4fort** [comment]
> I had the same issue but was able to resolve it by creating a new project before attempting to add my data source.

Regardless of changing directories and location to any directories and location option in settings; This one worked for me.
