### ISSUE TITLE
Failed to save settings. Please restart

### ISSUE THREAD

**Issue by CristianArean** [flathub/com.jetbrains.DataGrip#126]
I have this issue that when i connect to a database, It cannot save it for later and prompts this message Failed to save settings. Please restart.
![image](https://github.com/user-attachments/assets/80c0726b-ba5f-4d04-88e1-5066daf075b8)

Maybe it's important to notice that I'm connecting to a MS Sql server by localhost

**Comment by x80486** [comment]
Take a look at the closed issues. This is because you are in the default location/workspace that's created when the application starts, and by default it's created inside the sandbox.

Not the greatest experience, but as soon as you create your workspace in your home directory, you will be all set.
