### ISSUE TITLE
Cant save foreign key in MariaDB database table

### ISSUE THREAD

**Issue by peon501** [flathub/com.jetbrains.DataGrip#14]
Cant save foreign key in MariaDB database table.
I press execute, wait, and nothing... Refreshed after that. Didn't got any changes.
Did it a couple of times, but nothing...

**Comment by x80486** [comment]
Are you able to communicate with the database? If so, I think it's not related with the Flatpak package, but probably something with DataGrip in general, although I don't see that problem while running a quick test; I can create table(s) with constraints, alter the table(s) and delete them, etc.

![image](https://user-images.githubusercontent.com/34633617/61843988-daf90f80-ae6b-11e9-8806-1bf1bbe6378b.png)

**Comment by x80486** [comment]
I'm going to close this one since I haven't had any feedback in a while...and nobody else have faced (or reported) something similar.

Feel free to reopen it if you run into something similar again.
