### ISSUE TITLE
Unable to set the path to pg_dump or psql executable

### ISSUE THREAD

**Issue by maaattes** [flathub/com.jetbrains.DataGrip#21]
On my system (Fedora 30) `which pg_dump` returns `/usr/bin/pg_dump` and `which psql` returns `/usr/bin/psql`
However, I'm unable to set this path in Datagrip (see attached screenshot).
![Path to pg_dump](https://user-images.githubusercontent.com/52661914/65038083-6d3f0080-d94f-11e9-8eb7-6fea88966498.png)
![Path to psql](https://user-images.githubusercontent.com/52661914/65038257-de7eb380-d94f-11e9-843d-187e58273968.png)

Is this possibly related to the [sandbox permissions](http://docs.flatpak.org/en/latest/sandbox-permissions.html)? What can I do?

**Comment by x80486** [comment]
Indeed! Since you are using a binary on the host, it is not going to find it in that location.

If you find a way to install `pg_dump` and `psql` in your `HOME` directory, it's _more likely_ this would work without any workarounds – https://www.enterprisedb.com/ provides PostgreSQL binaries; you can unpack the one (with the version you want to use) somewhere in your `HOME` and give it a try.

You can also try to override (or add/expand) the Flatpak permissions to `host`: `--filesystem=host`, and probably, although it usually never works, you would be able to reference those binaries via `/var/run/host/usr/bin/pg_dump`, etc.

**Comment by TingPing** [comment]
@x80486 	All of this is terrible advice...

You either use `flatpak-spawn --host` or you bundle the tool. There is no other solution.

**Comment by x80486** [comment]
Well, there you go then! In any case, @maaattes, now you have plenty of options...insane and sane ones included :rofl:

**Comment by maaattes** [comment]
@TingPing Could you elaborate on how this can be done? Could I, in theory, just write some kind of wrapper script? Like `flatpak-spawn --host --clear-env pg_dump "$@"` or something like this and place it somewhere? Even if I think bundling pg_basebackup, pg_dump, pg_dumpall and pg_restore, would probably be the better way :thinking:

**Comment by jesse-a-reilly** [comment]
For those coming here from Google, here's how to create a wrapper script.

Run `sudo flatpak override com.jetbrains.DataGrip --talk-name=org.freedesktop.Flatpak`
This allows datagrip to break out of the sandbox.

Create a wrapper script somewhere in your home directory, name it `pg_dump.sh`, and give it execute permissions.

The contents of the script:
`exec flatpak-spawn --host --watch-bus --clear-env pg_restore "$@"`

In Datagrip, set the path to pg_dump to the newly created wrapper script.

**Comment by Sylk** [comment]
This solution doesn't inspire joy.

**Comment by vahe-nikoghosyan** [comment]
``` sudo apt-get install postgresql-client ```

**Comment by vascofff** [comment]
try just `/bin/pg_dump` path

**Comment by d00rsfan** [comment]
After 3 years bug is still persists, IDEA with wsl, "Path to executable is wrong" on hover (after choose file in **Browse...** modal.
//wsl$/Ubuntu/usr/bin/pg_dump

**Comment by GR1NYAoff** [comment]
> Indeed! Since you are using a binary on the host, it is not going to find it in that location.
> 
> If you find a way to install `pg_dump` and `psql` in your `HOME` directory, it's _more likely_ this would work without any workarounds – https://www.enterprisedb.com/ provides PostgreSQL binaries; you can unpack the one (with the version you want to use) somewhere in your `HOME` and give it a try.
> 
> You can also try to override (or add/expand) the Flatpak permissions to `host`: `--filesystem=host`, and probably, although it usually never works, you would be able to reference those binaries via `/var/run/host/usr/bin/pg_dump`, etc.

Thanks, it works for me, you can find ready-made binaries by direct link:
https://www.enterprisedb.com/download-postgresql-binaries-1
