### ISSUE TITLE
Add git and gpg support

### ISSUE THREAD

**Issue by junjieyuan** [flathub/com.jetbrains.DataGrip#69]
Since [DataGrip 2020.2](https://www.jetbrains.com/zh-cn/datagrip/whatsnew/2020-2/), git are bundled.

Can we copy flathub/com.jetbrains.IntelliJ-IDEA-Ultimate@770fea8a9c18615ba75a4ccdfd5c36a60144d060 to enable git and gpg?

**Comment by x80486** [comment]
That change will allow to sign commits, but you should be able to use Git regardless.

**Comment by junjieyuan** [comment]
Oh, I see, ``org.freedesktop.Sdk`` contains git and ``org.freedesktop.Platform`` not. I will issue a merge request later.

**Comment by Rennarde1312** [comment]
Hi, sorry to bother but the PR seems to be in draft for a long time.
I use PHPStorm and IntelliJ IDEA wich both picked my git setup right of the bat.

**Comment by hbongen** [comment]
Please fix this issue. It would be really nice to have git inside the flatpak. Should I open another PR, or could you manage to get it merged?

**Comment by x80486** [comment]
This is almost ready to be merged. Would you be able to test this test build from pull request `86` and provide your feedback?

**Comment by hbongen** [comment]
I Have checkout the branch and build it locally. Git works fine for me. Would be really happy if you accpt it and publish the changes.
